### ISSUE TITLE
Bug: Activating lightsource on an actor without a token throws error

### ISSUE THREAD

**Issue by bakbakbakbakbak** [Muttley/foundryvtt-shadowdark#199]
When activating a lightsource on an actor missing a token, the console logs these messages:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'document')
    at ActorSD.turnLightOn (ActorSD.mjs:472:24)
    at ActorSD.toggleLight (ActorSD.mjs:449:9)
    at PlayerSheetSD._onToggleLightSource (PlayerSheetSD.mjs:272:14)
```

**Comment by Muttley** [comment]
Maybe should pop up a message to the user and not do anything if there's no token.
