### ISSUE TITLE
Attack roles fail when Dice So Nice module is enabled

### ISSUE THREAD

**Issue by Muttley** [Muttley/foundryvtt-shadowdark#86]
```javascript
DiceNotation.js:14 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dice')
    at new DiceNotation (DiceNotation.js:14:9)
    at Dice3D.showForRoll (Dice3D.js:613:24)
    at RollSD._rollDiceSoNice (RollSD.mjs:639:5)
    at RollSD.mjs:613:18
    at new Promise (<anonymous>)
    at RollSD._renderRoll (RollSD.mjs:597:10)
    at async RollSD.RollD20Dialog (RollSD.mjs:396:10)
    at async ItemSD.rollItem (ItemSD.mjs:65:3)
```

**Comment by Muttley** [comment]
Happens for both NPC and Player attack rolls.
