### ISSUE TITLE
Unable to delete items from gem bag

### ISSUE THREAD

**Issue by johncarney** [Muttley/foundryvtt-shadowdark#976]
Gems cannot be deleted from a character's gem bag.

<table>
<tr><td>Foundry version</td><td>12.331</td></tr>
<tr><td>Shadowdark system version</td><td>3.2.2</td></tr>
<tr><td>Enabled modules</td><td>None</td></tr>
</table>

# Steps to reproduce

1. Create a Shadowdark game world. Do not enable any modules.
2. Create a character
3. Add one or more items to the character's gem bag
4. Right-click on an item in the gem bag.
5. Select "delete item"

At this point I would expect the item to be removed from the gem bag. However nothing happens. In the developer console the following error message appears.

```
GemBagSD.mjs:134 Uncaught ReferenceError: tr is not defined
    at Object.callback (GemBagSD.mjs:134:21)
    at #onClickItem (foundry.js:68634:11)
    at HTMLElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)
```

# Work around

In order to remove an item from a character's gem bag you can *sell* it, then manually remove the appropriate number of coins from the character's inventory.

# Video

https://github.com/user-attachments/assets/9cb30300-4542-4670-88fa-41cccd490ba6

**Comment by johncarney** [comment]
Looking at the code, I think `tr.data` is meant to be `element.data`:
```javascript
			{
				name: game.i18n.localize("SHADOWDARK.sheet.general.item_delete.title"),
				icon: '<i class="fas fa-trash"></i>',
				condition: element => canEdit(element),
				callback: element => {
					const itemId = tr.data("item-id");
					this._onItemDelete(itemId);
				},
			},
```

**Comment by Muttley** [comment]
Many thanks for the thorough bug report.  This will be fixed in the next release.
